# Generated by Django 2.2.3 on 2019-09-03 06:12

from django.db import migrations, models
import django_s3_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='md5',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='source',
            field=models.ImageField(storage=django_s3_storage.storage.S3Storage(), upload_to='images'),
        ),
    ]
