# Generated by Django 2.2.3 on 2019-09-03 12:25

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img', '0003_auto_20190903_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='images_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='image',
            name='used_by',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.jsonb.JSONField(), default=list, size=None),
        ),
    ]
